### ISSUE TITLE
python manage.py createdb fails with django.db.utils.ProgrammingError: relation "auth_user" does not exist

### ISSUE THREAD

**Issue by orotau** [stephenmcd/mezzanine.jupo.org#6]
Working in a virtual environment with PosgreSQL

git clone https://github.com/stephenmcd/mezzanine.jupo.org.git mezzanine_jupo_org_2
pip install paver
pip install -r requirements.txt
python manage.py createdb

results in this ...

/home/graham/Virtual-Environments/readme-work-2/src/mezzanine/mezzanine/utils/conf.py:51: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
<string>:8: (WARNING/2) Duplicate explicit target name: "mission healthcare".
/home/graham/Virtual-Environments/readme-work-2/src/mezzanine/mezzanine/generic/fields.py:6: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericRelation

Operations to perform:
  Synchronize unmigrated apps: gnotty, mobile, demo, boot, filebrowser_safe, sitemaps, compressor, staticfiles, accounts, grappelli_safe
  Apply all migrations: shop, core, redirects, django_comments, sessions, admin, twitter, galleries, sites, auth, blog, generic, contenttypes, conf, forms, pages
Synchronizing apps without migrations:
  Creating tables...
    Creating table gnotty_ircmessage
    Creating table demo_profile
    Running deferred SQL...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/graham/Virtual-Environments/readme-work-2/src/mezzanine/mezzanine/core/management/commands/createdb.py", line 60, in handle
    interactive=self.interactive)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/graham/Virtual-Environments/readme-work-2/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "auth_user" does not exist

I will have a look around for solutions...
g

**Comment by orotau** [comment]
When I restrict Django to 1.7.8 I don't get the above error.
However, when I go to the home page (127.0.0.1:8000) I get another error
'compress' is not a valid tag library: ImportError raised loading compressor.templatetags.compress: cannot import name simplejson
